### ISSUE TITLE
文章

### ISSUE THREAD

**Issue by Season-Chan** [zhiyiYo/Specular-Removal#1]
你好，请问这是哪篇文章的代码实现呢？是《A Multi-Task Network for Joint Specular Highlight Detection and Removal》？还是《CDFF-Net: Cumulative Dense Feature Fusion for Single Image Specular Highlight Removal》呢？

**Comment by zhiyiYo** [comment]
代码和两篇的都不一样，因为这只是暑假实习的划水作品😅

**Comment by Season-Chan** [comment]
噢噢好的，那请问有这个模型的描述图片吗？想学习一下；与CVPR2021那篇相比（假设为10分），去高光的效果好不好（本代码的效果大概为几分）？

**Comment by zhiyiYo** [comment]
本代码完全不敢和人家相比，毕竟这只是对付导师用的😆，下面是模型的结构
![image](https://user-images.githubusercontent.com/65096819/149904947-6831251c-6efa-4391-9651-df90fd40f85e.png)

**Comment by Season-Chan** [comment]
好的，非常感谢大佬！CVPR21那篇文章没有开源，效果再好也比较难进一步学习。感觉大佬给出来的去高光效果结果图也很不错呀！这份代码里面是不是没有量化指标相关的代码？

**Comment by zhiyiYo** [comment]
之前用了结构相似性和峰值信噪比来衡量，但是代码好像被我删了，因为这个代码很简单，skimage 有提供现成的函数

**Comment by Season-Chan** [comment]
噢噢，好的。谢谢你！
