### ISSUE TITLE
test environment时出错

### ISSUE THREAD

**Issue by Season-Chan** [zhiyiYo/Specular-Removal#2]
你好！我在Test environment 时，触发了错误“图像太大啦，请缩小图像大小后再尝试~~”，我没有修改remove_specular.py中的任何代码，这是为什么呢？resource/images目录下的文件图片大小为200x200，我将图像尺寸缩小一半后（即100x100），还是触发同样的错误。这个网络能处理图片的尺寸是固定大小的吗？如果是的话，大小应该为多小？

**Comment by Season-Chan** [comment]
不知道是不是因为服务器显存不足导致的，因为我在服务器测试的时候，有人正在训练模型，显存还剩下1000MiB左右。

**Comment by zhiyiYo** [comment]
图像大小是随意的，训练的时候被裁剪到192*192大小的，推理的时候长和宽被填充为32的倍数，触发错误应该是显存不够导致的，可以考虑把batch_size弄小点

**Comment by zhiyiYo** [comment]
不过你也可以把 exception_handler 装饰器注释掉看看到底是怎么报错的

**Comment by Season-Chan** [comment]
好的。问题已经解决了，报错的原因应该是pytorch版本和cuda版本没有匹配。谢谢解答！
