### ISSUE TITLE
您好，请问这部分的代码是在做什么工作

### ISSUE THREAD

**Issue by RNGrunshen** [zhiyiYo/Specular-Removal#3]
![1](https://user-images.githubusercontent.com/107196233/178670761-156728af-0e3e-4a42-9cbf-6abae6b43008.png)

    def forward(self, x, M):
        """
        Parameters
        ----------
        x: Tensor of shape `(N, C, H, W)`
            特征图

        M: Tensor of shape `(N, 1, H, W)`
            图像蒙版，高光区域的像素值为 `0`
        """
        M = self.conv_M(M)
        index = M == 0
        M[index] = 1
        x = self.conv_I(M*x)
        x = F.relu(self.bn(x/M))
        M = M.masked_fill(index, 0)
        return x, M

**Comment by zhiyiYo** [comment]
可以结合网络结构图来理解
![image](https://user-images.githubusercontent.com/65096819/149904947-6831251c-6efa-4391-9651-df90fd40f85e.png)
